WebApp/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KnjigeRedis;

namespace WebApp.Controllers
{
    public class BookController : Controller
    {
        DataManager manager = new DataManager();
        bool first = true;
        int komentariBroj = 2;
        // GET: Book
        public ActionResult Index()
        {
          //  List<List<string>> l = new List<List<string>>();
            List<object> l = new List<object>();
            Knjiga k = manager.getKnjiga("666");
            
            double o = manager.getOcena("666");
            List<List<string>> komentari = manager.getKomentarKnjiga("666",2);
           

            List<string> knjiga = new List<string>();
            knjiga.Add(k.ISBN);
            knjiga.Add(k.Ime);
            knjiga.Add(k.Autor);
            knjiga.Add(k.Datum.ToShortDateString());
            knjiga.Add(o.ToString());
            l.Add(knjiga);

            l.Add(komentari);



            return View(l);
        }
        public ActionResult GetKnjiga(FormCollection collection)
        {
     

            Knjiga k = manager.getKnjiga(Request.Form["isbn"]);
            if (k == null)
                return View("Index", null);
            if(first)
            manager.click(Request.Form["isbn"]);
          //  first = true;
            long cl=  manager.getClicks(Request.Form["isbn"]);
                double o = manager.getOcena(Request.Form["isbn"]);

            ViewBag.isbn = k.ISBN;
            ViewBag.ime = k.Ime;
            ViewBag.autor = k.Autor;
            ViewBag.datum = k.Datum.ToShortDateString();
            if (o == 0)
                ViewBag.ocena = "Nema ocene.";
            else
            ViewBag.ocena = o.ToString();
            ViewBag.pregledi = cl.ToString();

          
            List<List<string>> komentari = manager.getKomentarKnjiga(Request.Form["isbn"],komentariBroj);
       



                return View("Index",komentari);
            
        }
        public ActionResult GetKnjigaLink(string isbn)
        {


            Knjiga k = manager.getKnjiga(isbn);
            if (k == null)
                return View("Index", null);
            if(first)
            manager.click(isbn);
            //first = true;
            long cl = manager.getClicks(isbn);
            double o = manager.getOcena(isbn);
            List<List<string>> komentari = manager.getKomentarKnjiga(isbn,komentariBroj);
            ViewBag.isbn = k.ISBN;
            ViewBag.ime = k.Ime;
            ViewBag.autor = k.Autor;
            ViewBag.datum = k.Datum.ToShortDateString();
            
            if (o == 0)
                ViewBag.ocena = "Nema ocene.";
            else
            ViewBag.ocena = o.ToString();
            ViewBag.pregledi = cl.ToString();


            return View("Index", komentari);

        }
        public ActionResult PutKomentar(FormCollection collection)
        {
           string id= manager.komentarisi(Request.Form["isbn"], Request.Form["komentar"], Session["korisnik"].ToString());
            first = false;
            return GetKnjigaLink(Request.Form["isbn"]);
        }
        public ActionResult Like(FormCollection collection)
        {
            //manager.like(Request.Form["isbn"], Request.Form["user"],Session["korisnik"].ToString());
            string a = Request.Form["isbn"];
            string b= Request.Form["komentarId"];
            string c = Session["korisnik"].ToString();
            manager.like(Request.Form["isbn"], Request.Form["user"], Session["korisnik"].ToString(), Request.Form["komentarId"]);
            first = false;
            
            return GetKnjigaLink(Request.Form["isbn"]);
        }
        public ActionResult Unlike(FormCollection collection)
        {
            manager.unlike(Request.Form["isbn"], Request.Form["user"],Session["korisnik"].ToString(), Request.Form["komentarId"]);
            first = false;
            return GetKnjigaLink(Request.Form["isbn"]);
        }
        public ActionResult Nazad(FormCollection collection)
        {
            first = true;
            return RedirectToAction("Index", "Home");
        }
        public ActionResult PutOcena(FormCollection collection)
        {
            manager.oceni(Request.Form["isbn"], int.Parse(Request.Form["ocenaradio"]),Session["korisnik"].ToString());
            first = false;
            return GetKnjigaLink(Request.Form["isbn"]);
        }
        public ActionResult UcitajKomentare(FormCollection collection)
        {
            komentariBroj += 5;
            first = false;
            return GetKnjigaLink(Request.Form["isbn"]);
        }
        public ActionResult AddKorpa(FormCollection collection)
        {
            first = false;
            if (Session["korisnik"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            manager.addKorpa(Request.Form["isbn"], Session["korisnik"].ToString());
            TempData["dodato"] = "dodato";
            return GetKnjigaLink(Request.Form["isbn"]);
        }
        public ActionResult KorpaPrikaz(FormCollection collection)
        {
            if (Session["korisnik"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            string[] sifre = manager.getKorpa(Session["korisnik"].ToString());
            if (sifre.Length > 0)
            {
                List<string> li = new List<string>();
                foreach(string s in sifre)
                {
                    Knjiga k = manager.getKnjiga(s);
                    string pom =  k.ISBN +" " + k.Ime + " " + k.Autor;
                    li.Add(pom);
                }
               
                return View("Korpa", li);
            }
            return View("Korpa",null);
        }
        public ActionResult RemoveKorpa(FormCollection collection)
        {
            if (Session["korisnik"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            manager.deleteFromKorpa(Session["korisnik"].ToString(), Request.Form["isbn"]);
            return RedirectToAction("KorpaPrikaz");
        }
        public ActionResult Naruci(FormCollection collection)
        {
            if (Session["korisnik"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Korisnik kor = new Korisnik
            {
                UserName=Session["korisnik"].ToString(),
                Ime=Request.Form["ime"],
                Prezime=Request.Form["prezime"],
                Adresa=Request.Form["adresa"],
                Telefon=Request.Form["telefon"]
            };
            manager.naruci(kor);
            TempData["naruceno"] = "naruceno";
            return RedirectToAction("KorpaPrikaz");
        }

    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KnjigeRedis;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        DataManager manager = new DataManager();
        List<Knjiga> lista;
        int brojKnjiga = 10;
        // GET: Home
        public ActionResult Index()
        {
            if(lista==null)
             lista = manager.getKnjige(brojKnjiga);
            List<List<string>> k = new List<List<string>>();
            foreach (Knjiga kn in lista)
            {
                if (kn == null)
                    continue;
                List<string> l=new List<string>();
                l.Add(kn.ISBN);
                l.Add( kn.Ime);
                l.Add(kn.Autor);
                l.Add(kn.Datum.ToShortDateString());

                k.Add(l);
             
            }
           // ViewBag.timeExpire = DateTime.UtcNow.AddSeconds(65);
            return View("Home",k);
        }
        public ActionResult UcitajKnjige(FormCollection collection)
        {
            brojKnjiga += 10;
            return Index();
        }
    }
}

WebApp/Controllers/KorisnikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KnjigeRedis;
using System.Web.SessionState;


namespace WebApp.Controllers
{
  //  [SessionTimeout]
    public class KorisnikController : Controller
    {
        DataManager manager = new DataManager();
        // GET: Korisnik
        public ActionResult Index()
        {
            
            return View();
        }
        public ActionResult IndexLog()
        {
            int g = 0;
            return View("Logovanje",g);
        }
        public ActionResult IndexReg()
        {
            int g = 0;
            return View("Registracija",g);
        }
        
        public ActionResult Logovanje(FormCollection collection)
        {
            bool pom = manager.login(Request.Form["username"], Request.Form["password"]);

            int g = 1;
            if (!pom)
                return View("Logovanje", g);
            Session["korisnik"] = Request.Form["username"];

              Session.Timeout = 3;
            //  var timeOut = 60;
            //  return RedirectToAction("Index", "Home",timeOut);
           // var timeExpire = DateTime.UtcNow.AddSeconds(65);
            
            return RedirectToAction("Index", "Home");


        }
      

        public ActionResult Registrovanje(FormCollection collection)
        {
            bool pom = manager.register(Request.Form["username"], Request.Form["password"]);
            int g = 1;
            if(!pom)
            return View("Registracija", g);
            return IndexLog();
        }

        public ActionResult LogOut(FormCollection collection)
        {
           
            manager.deleteKorpa(Session["korisnik"].ToString());
            Session["korisnik"] = null;
            return RedirectToAction("Index", "Home");

        }
        public ActionResult Nazad(FormCollection collection)
        {

            return RedirectToAction("Index", "Home");
        }
    }
}

WebApp/Views/Shared/Home.cshtml
@model List<List<string>>
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{


    var endTime = DateTime.UtcNow.AddSeconds(60);
    var timeRemaining = TimeSpan.FromTicks(endTime.Ticks - DateTime.UtcNow.Ticks).TotalSeconds.ToString("#");
}
        <script>


            var remSeconds =timeRemaining;
            var secondsCounter = remSeconds % 60;

            function formatNumber(number) {
                if (number < 10)
                    return '0' + number;
                else return '' + number;
            }

            function startTick() {
                document.getElementById('seconds').innerText = formatNumber( secondsCounter);
                document.getElementById('minutes').innerText = formatNumber(parseInt(remSeconds / 60));

                var _tick = setInterval(function () {
                    if (remSeconds > 0) {
                        remSeconds -= 1;
                        secondsCounter -= 1;
                        document.getElementById('seconds').innerText = formatNumber(secondsCounter);
                        document.getElementById('minutes').innerText = formatNumber(parseInt(remSeconds / 60));
                        if (secondsCounter == 0)
                            secondsCounter = 60;
                    }
                    else {
                        alert('Vasa sesija je istekla!');
                        clearInterval(_tick);
                    }
                }, 1000);

            }
            startTick();
        </script>
      
        
    

<div id="minutes"></div>
<div id="seconds"></div>
    <div class="row">

        <div class="col-xs-6 col-md-4">

            @{
                if (Session["korisnik"] != null)
                {
                    <h4> Dobro dosli, @Session["korisnik"] !</h4>
                }
            }

            <h3>Najnovije knjige </h3>
            <br />

            @foreach (List<string> item in Model)
            {
                <li>


                    <h5>ISBN: @item[0]</h5>
                    <h4>Naziv: </h4>
                    <h3 class="btn-link">
                        @Html.ActionLink(item[1], "GetKnjigaLink", "Book", new { isbn = item[0] }, null)
                    </h3>
                    <h5>Autor: @item[2]</h5>
                    <h6>Datum izdavanja: @item[3]</h6>

                    <br />
                </li>
            }
            @using (Html.BeginForm("UcitajKnjige", "Home", FormMethod.Post))
            {

                <button type="submit" class="btn btn-sm btn-circle ">Još</button>


            }
        </div>

        <div class="col-xs-6 col-md-4">
            @using (Html.BeginForm("GetKnjigaLink", "Book", FormMethod.Post))
            {
                <h3>Izaberite knjigu</h3>
                <br />
                <label>ISBN:</label>
                <br />
                <input class="form-control" type="text" name="isbn" id="isbn" />

                <br />
                <button type="submit" class="btn btn-lg btn-success">Izaberi</button>
            }
        </div>

    </div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Web Knjige</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body background="~/Content/Images/knjigamain.jpg">
   
    @*@{ 
        if (Session["korisnik"] != null)
        {

            var endTime = DateTime.UtcNow.AddSeconds( Session.Timeout*60);
            var timeRemaining = TimeSpan.FromTicks(endTime.Ticks - DateTime.UtcNow.Ticks).TotalSeconds.ToString("#");
    <script>
        
        
            var remSeconds =timeRemaining;
            var secondsCounter = remSeconds % 60;

            function formatNumber(number) {
                if (number < 10)
                    return '0' + number;
                else return '' + number;
            }

            function startTick() {
                document.getElementById('seconds').innerText = formatNumber( secondsCounter);
                document.getElementById('minutes').innerText = formatNumber(parseInt(remSeconds / 60));

                var _tick = setInterval(function () {
                    if (remSeconds > 0) {
                        remSeconds -= 1;
                        secondsCounter -= 1;
                        document.getElementById('seconds').innerText = formatNumber(secondsCounter);
                        document.getElementById('minutes').innerText = formatNumber(parseInt(remSeconds / 60));
                        if (secondsCounter == 0)
                            secondsCounter = 60;
                    }
                    else {
                        alert('Vasa sesija je istekla!');
                        clearInterval(_tick);
                    }
                }, 1000);

        } startTick();
    </script>
            }

        }*@


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("Knjige", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Registracija", "IndexReg", "Korisnik")</li>


                    <li>@Html.ActionLink("Prijavljivanje", "IndexLog", "Korisnik")</li>

                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>




                    @{
                        if (Session["korisnik"] != null)
                        {
                            <li class="nav-item active">@Html.ActionLink("Korpa", "KorpaPrikaz", "Book")</li>

                            <li class="nav-item active">@Html.ActionLink("Odjavi se", "LogOut", "Korisnik")</li>
                           @*<li class="nav-item active" id="minutes"> : </li>
                            <li class="nav-item active" id="seconds"> </li>*@
                            
                        }
                    }


                </ul>


            </div>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav"></ul>
        </div>
    </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Web Knjige</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


</body>
</html>